# Generated by Django 6.1.2 on 2026-10-07 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPriceDataset',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_row_count', models.PositiveIntegerField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_station_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.CharField(max_length=64)),
                ('price_usd_per_gallon', models.DecimalField(decimal_places=16, max_digits=24)),
                ('price_source_text', models.CharField(max_length=64)),
                ('source_row_numbers', models.JSONField(default=list)),
                ('source_names', models.JSONField(default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('geocoding_status', models.CharField(default='pending', max_length=20)),
                ('geocoding_source', models.CharField(blank=True, max_length=100)),
                ('geocoding_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('location_verified_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='routes.fuelpricedataset')),
            ],
        ),
        migrations.CreateModel(
            name='FuelPriceSourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('physical_line_number', models.PositiveIntegerField()),
                ('raw_values', models.JSONField()),
                ('normalized_values', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=16)),
                ('issue', models.CharField(blank=True, max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rows', to='routes.fuelpricedataset')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_rows', to='routes.fuelstation')),
            ],
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['dataset', 'state', 'city'], name='routes_fuel_dataset_89b235_idx'),
        ),
        migrations.AddConstraint(
            model_name='fuelstation',
            constraint=models.UniqueConstraint(fields=('dataset', 'source_station_id'), name='unique_station_per_dataset'),
        ),
        migrations.AddIndex(
            model_name='fuelpricesourcerow',
            index=models.Index(fields=['dataset', 'status'], name='routes_fuel_dataset_02a891_idx'),
        ),
        migrations.AddConstraint(
            model_name='fuelpricesourcerow',
            constraint=models.UniqueConstraint(fields=('dataset', 'row_number'), name='unique_source_row_per_dataset'),
        ),
    ]
